# Site wide configuration
theme: jekyll-theme-perfolio

destination: docs

url: "https://career.rossgodwin.com"
baseurl: ""

title: Ross Godwin
description: Personal website about Ross Godwin' career
author: Ross Godwin

google_analytics_measurement_id: G-X190CB39TW

linkedin:
  display-url: linkedin.com/ross-godwin
  url: https://www.linkedin.com/in/ross-godwin

github:
  display-url: github.com/rossgodwin
  url: https://www.github.com/rossgodwin
  website-repo: career.rossgodwin.com
  ctc-repo: app.cheapthycable.com

cheapthycable:
  display-url: cheapthycable.com
  url: https://cheapthycable.rossgodwin.com

# Jekyll configuration
permalink: /:categories/:title/
show_drafts: false
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
include:
  - _pages
exclude:
  - .bundle
  - .jekyll-cache
  - .gitignore
  - .project
  - _drafts
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Photoshop/
  - vendor/bundle/
  - TODO

excerpt_separator: <!--more-->

sass:
  style: :compressed

# Collections
collections_dir: articles
collections:
  howtos:
    output: true
    permalink: /:collection/:path/
  notes:
    output: true
    permalink: /:collection/:path/

# Plugings
gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-liquify

plugins:
  - jekyll-sitemap
  - jekyll-gist

defaults:
  - scope:
      path: docs/*
    values:
      sitemap: false
  - scope:
      path: assets/*
    values:
      sitemap: false

# Plugin: Pagination (jekyll-paginate-v2)
pagination:
  enabled: true
  per_page: 3
  permalink: '/:num/'
  title: ':title | :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail: 
    before: 2
    after: 2

# Plugin: Auto Pages (jekyll-paginate-v2)
autopages:
  enabled: true
  tags:
    enabled: true
    layouts:
      - autopage_tags.html
    permalink: /tag/:tag
  categories:
    enabled: false
    layouts:
      - autopage_category.html
  collections:
    enabled: false
    slugify:
      mode: 'ascii'
      cased: true
